### ISSUE TITLE
No features available: select more feature types or deselect auto features

### ISSUE THREAD

**Issue by RhettRautsaw** [marlonecobos/kuenm#21]
# Problem
I am currently using kuenm to test "all" f.clas models. This seems to work during the candidate model/calibration stage, but when certain models make it into the final model set, I get the error message:

```No features available: select more feature types or deselect auto features```

My tests suggest this to be models with only "p" as the feature class. In other words, product-only models appear to always fail. Therefore, I think these need to be excluded from your "all" option for feature class testing. Based on this post on the Maxent Google Group, threshold-only models "t" may have the same issue (https://groups.google.com/g/maxent/c/i7_z7d1Pvj4/m/Wlo6JvvRAwAJ)

# Solution for Users
```
f_clas <- c("l", "q", "h", "lq", "lp", "lt", "lh", "qp", "qt", "qh", "pt", "ph", "th", "lqp", "lqt", "lqh", "lpt", "lph", "lth", "qpt", "qph", "qth", "pth", "lqpt", "lqph", "lqth", "lpth", "qpth", "lqpth")
```

**Comment by marlonecobos** [comment]
The reason may be related to the number of points you are using. P and T are features that require a certain number of points to be used. The maxent manual should explain this. You can either change other parameters of maxent using `args` in the function or make a vector of more relevant feature classes that you would like to use.

**Comment by RhettRautsaw** [comment]
Could you elaborate on what other parameters might be able to be changed? One of the species I am working with is incredibly abundant, so I can't imagine it's the number of points...the other species where I'm getting this error for "p" models I could see number of points being fair. Also could you post the maxent manual here? All I am finding are tutorials that barely mention these feature classes.

**Comment by marlonecobos** [comment]
Here a Maxent tutorial.
https://biodiversityinformatics.amnh.org/open_source/maxent/Maxent_tutorial2017.pdf

You can see details of Maxent when clicking the help button in the GUI of Maxent.

If you use p, you need at least two variables, because you are asking for product responses. 
If you see the GUI of Maxent, in settings, under experimental, you will see the number of records needed for certain feature classes to work.

In the function of kuenm you can change the argument `args` to set the parameters that are described almost at the end of details in the documentation of the function.

**Comment by nlzjj** [comment]
How did you solve this problem?@RhettRautsaw
